### PR TITLE
added onboarding design and language to home page, updated home and global styles

### PR DESCRIPTION
**Pull request by adebigare**
Fixed lint errors from previously failed pull request. Should be ready to deploy.

### CODE REVIEW

**Comment by isaacdurazo** [comment]
I just reviewed this PR and it's looking good. Thanks, @adebigare!

Something I would suggest (that not necessarily should stop us from merging this), is to have some sort of visual break in the home page between blocks. I was thinking something like this:

screenshot-ajl

**Comment by adebigare** [comment]
I love it!

**Comment by boazsender** [comment]
Cool, @adebigare, if you implement that in this PR, we can merge the whole thing.

**Comment by adebigare** [comment]
Ok style updates completed and ready for hopeful merge!

**Comment by boazsender** [comment]
Yay, we just landed @adebigare first patch to the project!!!

**Pull request merged**
