### PR TITLE
respond to annotations post with new workload and then consume it

### PR DESCRIPTION
**Pull request by boazsender**

### CODE REVIEW

**Comment by boazsender** [comment]
ping @gnarf @kadamwhite

**Comment by boazsender** [comment]
@kadamwhite there is a bug in this PR where the app is sending all annotations from all prior workloads back instead of just the current workload. is it possible to clear prior workloads from the store after they have been posted and before a new workload is loaded in? Where would I do that?

**Comment by boazsender** [comment]
I gave it a shot by `state.demographics.answers = {};`ing the workload out of the state in the `selectWorkload` selector. Linter is barking, but I couldn't figure out any other place to do this. 

The old answers need to be cleared out of the state before the new ones are loaded in so that they aren't all resent on the subsequent submisison.

**Comment by boazsender** [comment]
Moved the state clearing to the right place. I think this is good to merge

**Comment by kadamwhite** [comment]
Reviewing

**Comment by kadamwhite** [comment]
Needs unit tests; I'll implement those to validate that I understand the API correctly

**Comment by kadamwhite** [comment]
Added tests, reviewed the change and I'm +1: once Travis is green, this is ready to 🚢 !

**Pull request merged**
