### PR TITLE
Log timestamps

### LINKED ISSUE #90: Record timestamp in image_annotation

### PR DESCRIPTION
**Pull request by gnarf**
Closes #90 

* Logs time that workload is given to user
* Logs time that annotation is recorded

### CODE REVIEW

**Comment by tkellen** [comment]
If we want `updated_at` too, we can add this:
```sql
CREATE OR REPLACE FUNCTION updated_at() RETURNS TRIGGER AS $$
  BEGIN
    IF (NEW != OLD) THEN
      NEW.updated_at = CURRENT_TIMESTAMP;
      RETURN NEW;
    END IF;
    RETURN OLD;
  END;
$$ LANGUAGE plpgsql;
```

plus this for each table that uses it:

```
CREATE TRIGGER updated_at BEFORE UPDATE ON <tablename>
  FOR EACH ROW EXECUTE PROCEDURE updated_at();
```

**Comment by tkellen** [comment]
:+1: otherwise

**Comment by gnarf** [comment]
We might want an "updated_at" for workloads instead of "created_at" on actual annotations...

Gonna think it out... This current method totally works to get "submission" timestamp and partially "time spent annotating" (though we were thinking about also recording the time spent looking at the image before annotating.

**Comment by gnarf** [comment]
I'm gonna close this, I need to tweak other things about workload and how it works anyway.

**Comment by gnarf** [comment]
Alright I pushed a new commit here that restructures and now stores `created_at` and `submitted_at` on workload, but no other timestamps.

**Comment by kadamwhite** [comment]
Not necessarily needed but we could consider implementing Google Analytics events for this too

**Comment by gnarf** [comment]
> Not necessarily needed but we could consider implementing Google Analytics events for this too

#141

**Comment by boazsender** [comment]
+1

**Pull request merged**
