### PR TITLE
Score workloads

### PR DESCRIPTION
**Pull request by gnarf**
Contains #83 as well, but this scores the workloads based on the number of correct selected truths on a scale of 0 to 1.

### CODE REVIEW

**Comment by boazsender** [comment]
When pull and run this, and get images wrong, I get the following error:

```{"error":{"httpStatus":"500","title":"Internal Server Error","message":"Client Error","name":"RequestError","errors":[{"message":"cannot determine type of empty array"}]}}```

Is this correct?

**Comment by gnarf** [comment]
> Is this correct?

no, is it possible that you've run out of "knowns" to be fetching in your session? 

The "empty array" is probably because you've already completed all the `known` entries in the database and there are no more `knownImageIds` -- I added some extra logging here, also I'm gonna rebase this...

**Comment by boazsender** [comment]
I think that is what happened @gnarf. perhaps we should handle that differently? Like not send a workload if we don't have 2/3 knowns, but instead send a message that 'we are out of workloads, check back soon'?

**Comment by gnarf** [comment]
I made #100 to track that bug @boazsender but I'm gonna land this to use it as the base for the DB renaming spree

**Pull request merged**
